[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:eva-web]
directory=/app
command=gunicorn -k gevent -w 1 -b 0.0.0.0:8420 app:app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/eva-web.out.log
stderr_logfile=/var/log/supervisor/eva-web.err.log
environment=PYTHONUNBUFFERED="1"